[profile.default]
  evm_version = "paris"
  fuzz = { runs = 50 }
  optimizer = true
  optimizer_runs = 10_000_000
  remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "@murky/=lib/murky/",
  ]
  solc_version = "0.8.24"
  verbosity = 3

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  zksync = "${ZKSYNC_RPC_URL}"
