/**
 * assemble.ts — merge the L2 and L1 deployment artifacts into a single cli-tool config
 * (governance.json) and a human-readable deployed-addresses.md.
 *
 * Argv: <l2-governance.json> <l1-governance.json> <out-config.json> <out-addresses.md>
 * Env:  L1_RPC, L2_RPC (recorded into the config so the cli tools work out of the box)
 */
import * as fs from "fs";

function main() {
  const [l2Path, l1Path, outCfg, outMd] = process.argv.slice(2);
  const l2 = JSON.parse(fs.readFileSync(l2Path, "utf8"));
  const l1 = JSON.parse(fs.readFileSync(l1Path, "utf8"));

  const cfg = {
    l1Rpc: process.env.L1_RPC || "https://ethereum-sepolia-rpc.publicnode.com",
    l2Rpc: process.env.L2_RPC || "https://rpc.zksync-era-testnet.zksync.dev/",
    chainId: l2.chainId,
    zkToken: l2.zkToken,
    timelock: l2.timelock,
    governor: l2.governor,
    governorDeployBlock: l2.governorDeployBlock,
    protocolUpgradeHandler: l1.protocolUpgradeHandler,
    securityCouncil: l1.securityCouncil,
    guardians: l1.guardians,
    emergencyUpgradeBoard: l1.emergencyUpgradeBoard,
    zkFoundationSafe: l1.zkFoundationSafe,
  };
  fs.writeFileSync(outCfg, JSON.stringify(cfg, null, 2));

  const md = `# ZKsync Governance — Deployed Contracts

Generated by \`redeploy.sh\`.

- **L1**: Ethereum Sepolia (chainId 11155111)
- **L2**: ZKsync Era testnet (chainId ${l2.chainId}) — \`${cfg.l2Rpc}\`

## L2 contracts (ZKsync Era testnet)

| Contract | Address |
|---|---|
| ZK token (ZkTokenV2, transparent proxy) | \`${l2.zkToken}\` |
| TimelockController (= L1 \`L2_PROTOCOL_GOVERNOR\`) | \`${l2.timelock}\` |
| ZkProtocolGovernor | \`${l2.governor}\` |
| Deployer / initial ZK holder | \`${l2.deployer}\` |

Initial mint: \`${l2.mintAmount}\` (raw, 18 decimals) minted to the deployer, which self-delegated
its voting power. Governor params: votingDelay ${l2.votingDelay}s, votingPeriod ${l2.votingPeriod}s,
quorum \`${l2.quorum}\`.

## L1 contracts (Sepolia)

| Contract | Address |
|---|---|
| ProtocolUpgradeHandler (TestnetProtocolUpgradeHandler, proxy) | \`${l1.protocolUpgradeHandler}\` |
| ProtocolUpgradeHandler implementation | \`${l1.protocolUpgradeHandlerImpl}\` |
| ProtocolUpgradeHandler ProxyAdmin | \`${l1.protocolUpgradeHandlerProxyAdmin}\` |
| SecurityCouncil (12 members) | \`${l1.securityCouncil}\` |
| Guardians (8 members) | \`${l1.guardians}\` |
| EmergencyUpgradeBoard | \`${l1.emergencyUpgradeBoard}\` |
| ZK Foundation Safe | \`${l1.zkFoundationSafe}\` |
| Wired L2_PROTOCOL_GOVERNOR (L2 timelock) | \`${l1.l2ProtocolGovernor}\` |
| Chain diamond (ZKSYNC_ERA) | \`${l1.zksyncEra || "0xD3bc4353957bc0F138318384aa207C708A9455C4"}\` |

### Security Council member safes (1-of-1 Gnosis Safes, owner = \`${process.env.SAFE_OWNER || "0xD64e136566a9E04eb05B30184fF577F52682D182"}\`)

${(l1.securityCouncilMembers || []).map((m: string) => `- \`${m}\``).join("\n")}

### Guardian member safes (1-of-1 Gnosis Safes, same owner)

${(l1.guardiansMembers || []).map((m: string) => `- \`${m}\``).join("\n")}
`;
  fs.writeFileSync(outMd, md);
  console.log("Wrote", outCfg, "and", outMd);
}

main();
