name: L2 contracts ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    defaults:
      run:
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install zksync-foundry
        uses: ./.github/actions/install-zksync-foundry

      - name: Install dependencies
        run: forge install && npm install

      - name: Build
        run: npm run compile

      - name: Build l2-contracts (zkSync)
        run: forge clean && forge build --zksync

      - name: Install l1-contracts deps + build (EVM)
        working-directory: ./l1-contracts
        run: forge install && forge build

      - name: Save artifacts cache
        uses: actions/cache/save@v4
        with:
          key: artifacts-${{ github.sha }}
          path: |
            l1-contracts/out
            l2-contracts/zkout

  test:
    defaults:
      run:
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install zksync-foundry
        uses: ./.github/actions/install-zksync-foundry

      - name: Install dependencies
        run: forge install && npm install

      - name: Build
        run: npm run compile

      - name: Run forge tests
        run: npm run foundry-test

      - name: Run Era test node
        uses: dutterbutter/era-test-node-action@v0.1.3

      - name: Run hardhat tests
        run: npx hardhat test

  lint:
    defaults:
      run:
        shell: bash
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install zksync-foundry
        uses: ./.github/actions/install-zksync-foundry

      - name: Install dependencies
        run: forge install

      - name: Install scopelint
        uses: engineerd/configurator@v0.0.8
        with:
          name: scopelint
          repo: ScopeLift/scopelint
          fromGitHubReleases: true
          version: latest
          pathInArchive: scopelint-x86_64-linux/scopelint
          urlTemplate: https://github.com/ScopeLift/scopelint/releases/download/{{version}}/scopelint-x86_64-linux.tar.xz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: |
          scopelint --version
          scopelint check

  hashes:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Restore artifacts cache
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          key: artifacts-${{ github.sha }}
          path: |
            l1-contracts/out
            l2-contracts/zkout

      - name: Install root deps
        run: yarn install --frozen-lockfile

      - name: Check AllContractsHashes.json is up to date
        run: yarn calculate-hashes:check
